blank_issues_enabled: false
contact_links:
  - name: EVM Sidechain docs
    url: https://docs.xrplevm.org
    about: Learn more about the EVM Sidechain.
  - name: Peersyst
    url: https://peersyst.com
    about: Contact us for any questions or support.
